server:
  port: 8080
  context-path: /

spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sbn?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
      username: root
      password: 111111

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: cn.bingoogolapple.sbn.model
logging:
  level:
    root: info
    cn.bingoogolapple.sbn: debug